### ISSUE TITLE
Question: dev setup

### ISSUE THREAD

**Issue by mat-l** [lnbits/nostr-relay-extension#14]
Hi,
Do you have a separated requirements.text and a short developer guide on how to starting with the nostr relay as a standalone version?
I would like to test and learn more about your repo without the overall lnbits complexity around.

Best regards
mat

**Comment by motorina0** [comment]
> Do you have a separated requirements.text and a short developer guide on how to starting with the nostr relay as a standalone version?

No, there is no `standalone` version of the relay at the moment.

One reason this relay exists as an extension to LNbits is that LNbits offers all the Lightning Network integration in order to have paid relays.

> I would like to test and learn more about your repo without the overall lnbits complexity around.

The repo itself is decoupled from the LNbits code base. You can explore this repo without touching the LNbits code base (that is the purpose of the extensions).

Please let me know if you have any particular problems.
